/*
 * Vulkan pipeline construction.
 *
 * Shader modules, descriptor set layouts, and graphics pipelines for all
 * draw types (solid, image, text, gradient, stencil, cover, blur).
 */
#include "vk_internal.h"
#include <vulkan/vulkan.h>
#include <stdlib.h>
#include <string.h>

/* shader binaries (generated by meson into build/src/) */
#include "solid_color_vert_spv.inc"
#include "solid_color_frag_spv.inc"
#include "image_vert_spv.inc"
#include "image_frag_spv.inc"
#include "text_frag_spv.inc"
#include "gradient_vert_spv.inc"
#include "gradient_frag_spv.inc"
#include "stencil_frag_spv.inc"
#include "blur_frag_spv.inc"

/* ------------------------------------------------------------------ */
/*  Shader modules                                                    */
/* ------------------------------------------------------------------ */

VkShaderModule make_shader_module(vk_renderer *vk, const uint32_t *code, size_t size)
{
    VkShaderModuleCreateInfo ci = {
        .sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = size,
        .pCode    = code,
    };
    VkShaderModule mod = VK_NULL_HANDLE;
    FLUX_VK_CHECK(vkCreateShaderModule(vk->device.device, &ci, nullptr, &mod));
    return mod;
}

/* ------------------------------------------------------------------ */
/*  Pipeline creation helper                                          */
/* ------------------------------------------------------------------ */

bool make_pipeline_core(
    vk_renderer *vk,
    VkPipelineLayout layout,
    VkRenderPass render_pass,
    const uint32_t *vert_spv, size_t vert_size,
    const uint32_t *frag_spv, size_t frag_size,
    size_t vertex_stride,
    const VkVertexInputAttributeDescription *attrs, uint32_t attr_count,
    VkBool32 blend_enable,
    VkBlendFactor src_color, VkBlendFactor dst_color,
    VkBlendFactor src_alpha, VkBlendFactor dst_alpha,
    VkColorComponentFlags color_write_mask,
    VkStencilOp stencil_pass_op,
    VkCompareOp stencil_compare_op,
    uint32_t stencil_write_mask,
    uint32_t stencil_reference,
    VkPipeline *out_pipeline)
{
    VkDevice dev = vk->device.device;
    VkShaderModule vert = make_shader_module(vk, vert_spv, vert_size);
    VkShaderModule frag = make_shader_module(vk, frag_spv, frag_size);
    if (!vert || !frag) goto fail;

    VkPipelineShaderStageCreateInfo stages[2] = {
        { .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, .stage = VK_SHADER_STAGE_VERTEX_BIT,   .module = vert, .pName = "main" },
        { .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, .stage = VK_SHADER_STAGE_FRAGMENT_BIT, .module = frag, .pName = "main" },
    };

    VkVertexInputBindingDescription binding = {
        .binding = 0, .stride = (uint32_t)vertex_stride, .inputRate = VK_VERTEX_INPUT_RATE_VERTEX,
    };
    VkPipelineVertexInputStateCreateInfo vi = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
        .vertexBindingDescriptionCount   = 1,
        .pVertexBindingDescriptions      = &binding,
        .vertexAttributeDescriptionCount = attr_count,
        .pVertexAttributeDescriptions    = attrs,
    };

    VkPipelineInputAssemblyStateCreateInfo ia = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
        .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
    };
    VkPipelineViewportStateCreateInfo vp = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
        .viewportCount = 1, .scissorCount = 1,
    };
    VkPipelineRasterizationStateCreateInfo rs = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
        .polygonMode = VK_POLYGON_MODE_FILL, .cullMode = VK_CULL_MODE_NONE,
        .frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE, .lineWidth = 1.0f,
    };
    VkPipelineMultisampleStateCreateInfo ms = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
        .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
    };
    VkPipelineColorBlendAttachmentState blend_att = {
        .blendEnable         = blend_enable,
        .srcColorBlendFactor = src_color, .dstColorBlendFactor = dst_color, .colorBlendOp = VK_BLEND_OP_ADD,
        .srcAlphaBlendFactor = src_alpha, .dstAlphaBlendFactor = dst_alpha, .alphaBlendOp = VK_BLEND_OP_ADD,
        .colorWriteMask      = color_write_mask,
    };
    VkPipelineColorBlendStateCreateInfo cb = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
        .attachmentCount = 1, .pAttachments = &blend_att,
    };
    VkPipelineDepthStencilStateCreateInfo ds = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
        .depthTestEnable  = VK_FALSE,
        .depthWriteEnable = VK_FALSE,
        .stencilTestEnable = VK_TRUE,
        .front = {
            .failOp = VK_STENCIL_OP_KEEP, .passOp = stencil_pass_op, .depthFailOp = VK_STENCIL_OP_KEEP,
            .compareOp = stencil_compare_op, .compareMask = 0xFF, .writeMask = stencil_write_mask, .reference = stencil_reference,
        },
        .back = {
            .failOp = VK_STENCIL_OP_KEEP, .passOp = stencil_pass_op, .depthFailOp = VK_STENCIL_OP_KEEP,
            .compareOp = stencil_compare_op, .compareMask = 0xFF, .writeMask = stencil_write_mask, .reference = stencil_reference,
        },
    };
    VkDynamicState dyn_states[] = {
        VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR, VK_DYNAMIC_STATE_STENCIL_REFERENCE,
    };
    VkPipelineDynamicStateCreateInfo dyn = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO,
        .dynamicStateCount = 3, .pDynamicStates = dyn_states,
    };

    VkGraphicsPipelineCreateInfo pci = {
        .sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
        .stageCount = 2, .pStages = stages,
        .pVertexInputState   = &vi,
        .pInputAssemblyState = &ia,
        .pViewportState      = &vp,
        .pRasterizationState = &rs,
        .pMultisampleState   = &ms,
        .pDepthStencilState  = &ds,
        .pColorBlendState    = &cb,
        .pDynamicState       = &dyn,
        .layout              = layout,
        .renderPass          = render_pass,
        .subpass             = 0,
    };

    VkResult res = vkCreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &pci, nullptr, out_pipeline);
    FLUX_VK_CHECK(res);
    if (res != VK_SUCCESS)
        goto fail;

    vkDestroyShaderModule(dev, frag, nullptr);
    vkDestroyShaderModule(dev, vert, nullptr);
    return true;

fail:
    if (frag) vkDestroyShaderModule(dev, frag, nullptr);
    if (vert) vkDestroyShaderModule(dev, vert, nullptr);
    return false;
}

/* ------------------------------------------------------------------ */
/*  Descriptor set layout                                             */
/* ------------------------------------------------------------------ */

bool make_image_dsl(vk_renderer *vk)
{
    VkDescriptorSetLayoutBinding binding = {
        .binding = 0,
        .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
        .descriptorCount = 1,
        .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT,
    };
    VkDescriptorSetLayoutCreateInfo ci = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 1,
        .pBindings = &binding,
    };
    VkResult res = vkCreateDescriptorSetLayout(vk->device.device, &ci, nullptr, &vk->image_dsl);
    FLUX_VK_CHECK(res);
    return res == VK_SUCCESS;
}

/* ------------------------------------------------------------------ */
/*  Pipeline destruction                                              */
/* ------------------------------------------------------------------ */

void destroy_pipelines(vk_renderer *vk)
{
    VkDevice dev = vk->device.device;
    if (vk->blur_pipeline)           vkDestroyPipeline(dev, vk->blur_pipeline, nullptr);
    if (vk->blur_layout)             vkDestroyPipelineLayout(dev, vk->blur_layout, nullptr);
    if (vk->gradient_cover_pipeline) vkDestroyPipeline(dev, vk->gradient_cover_pipeline, nullptr);
    if (vk->solid_cover_pipeline)    vkDestroyPipeline(dev, vk->solid_cover_pipeline, nullptr);
    if (vk->fill_stencil_pipeline)   vkDestroyPipeline(dev, vk->fill_stencil_pipeline, nullptr);
    if (vk->stencil_pipeline)        vkDestroyPipeline(dev, vk->stencil_pipeline, nullptr);
    if (vk->stencil_layout)          vkDestroyPipelineLayout(dev, vk->stencil_layout, nullptr);
    if (vk->gradient_pipeline)       vkDestroyPipeline(dev, vk->gradient_pipeline, nullptr);
    if (vk->gradient_layout)         vkDestroyPipelineLayout(dev, vk->gradient_layout, nullptr);
    if (vk->text_pipeline)           vkDestroyPipeline(dev, vk->text_pipeline, nullptr);
    if (vk->text_layout)             vkDestroyPipelineLayout(dev, vk->text_layout, nullptr);
    if (vk->image_pipeline)          vkDestroyPipeline(dev, vk->image_pipeline, nullptr);
    if (vk->image_layout)            vkDestroyPipelineLayout(dev, vk->image_layout, nullptr);
    if (vk->solid_pipeline)          vkDestroyPipeline(dev, vk->solid_pipeline, nullptr);
    if (vk->solid_layout)            vkDestroyPipelineLayout(dev, vk->solid_layout, nullptr);
    if (vk->image_dsl)               vkDestroyDescriptorSetLayout(dev, vk->image_dsl, nullptr);

    vk->blur_pipeline = VK_NULL_HANDLE;
    vk->blur_layout = VK_NULL_HANDLE;
    vk->gradient_cover_pipeline = VK_NULL_HANDLE;
    vk->solid_cover_pipeline = VK_NULL_HANDLE;
    vk->fill_stencil_pipeline = VK_NULL_HANDLE;
    vk->stencil_pipeline = VK_NULL_HANDLE;
    vk->stencil_layout = VK_NULL_HANDLE;
    vk->gradient_pipeline = VK_NULL_HANDLE;
    vk->gradient_layout = VK_NULL_HANDLE;
    vk->text_pipeline = VK_NULL_HANDLE;
    vk->text_layout = VK_NULL_HANDLE;
    vk->image_pipeline = VK_NULL_HANDLE;
    vk->image_layout = VK_NULL_HANDLE;
    vk->solid_pipeline = VK_NULL_HANDLE;
    vk->solid_layout = VK_NULL_HANDLE;
    vk->image_dsl = VK_NULL_HANDLE;
    vk->pipelines_ready = false;
}

/* ------------------------------------------------------------------ */
/*  Pipeline creation (all draw types)                                */
/* ------------------------------------------------------------------ */

bool ensure_pipelines(vk_renderer *vk)
{
    if (vk->pipelines_ready) return true;
    VkDevice dev = vk->device.device;

    if (!make_image_dsl(vk)) return false;

    /* solid */
    {
        VkPushConstantRange push = {
            .stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
            .offset = 0, .size = sizeof(flux_solid_color_pc),
        };
        VkPipelineLayoutCreateInfo ci = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
            .pushConstantRangeCount = 1, .pPushConstantRanges = &push,
        };
        VkResult res = vkCreatePipelineLayout(dev, &ci, nullptr, &vk->solid_layout);
        FLUX_VK_CHECK(res);
        if (res != VK_SUCCESS) return false;

        VkVertexInputAttributeDescription attr = {
            .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0,
        };
        if (!make_pipeline_core(vk, vk->solid_layout, vk->render_pass,
                                flux_solid_color_vert_spv, sizeof(flux_solid_color_vert_spv),
                                flux_solid_color_frag_spv, sizeof(flux_solid_color_frag_spv),
                                sizeof(flux_solid_vertex), &attr, 1,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                0xF,
                                VK_STENCIL_OP_KEEP, VK_COMPARE_OP_EQUAL, 0x00, 0,
                                &vk->solid_pipeline)) return false;
    }

    /* image */
    {
        VkPushConstantRange push = {
            .stageFlags = VK_SHADER_STAGE_VERTEX_BIT, .offset = 0, .size = sizeof(flux_image_pc),
        };
        VkPipelineLayoutCreateInfo ci = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
            .setLayoutCount = 1, .pSetLayouts = &vk->image_dsl,
            .pushConstantRangeCount = 1, .pPushConstantRanges = &push,
        };
        VkResult res = vkCreatePipelineLayout(dev, &ci, nullptr, &vk->image_layout);
        FLUX_VK_CHECK(res);
        if (res != VK_SUCCESS) return false;

        VkVertexInputAttributeDescription attrs[2] = {
            { .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = offsetof(flux_image_vertex, pos) },
            { .location = 1, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = offsetof(flux_image_vertex, uv) },
        };
        if (!make_pipeline_core(vk, vk->image_layout, vk->render_pass,
                                flux_image_vert_spv, sizeof(flux_image_vert_spv),
                                flux_image_frag_spv, sizeof(flux_image_frag_spv),
                                sizeof(flux_image_vertex), attrs, 2,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                0xF,
                                VK_STENCIL_OP_KEEP, VK_COMPARE_OP_EQUAL, 0x00, 0,
                                &vk->image_pipeline)) return false;
    }

    /* text */
    {
        VkPushConstantRange push = {
            .stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
            .offset = 0, .size = sizeof(flux_text_pc),
        };
        VkPipelineLayoutCreateInfo ci = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
            .setLayoutCount = 1, .pSetLayouts = &vk->image_dsl,
            .pushConstantRangeCount = 1, .pPushConstantRanges = &push,
        };
        VkResult res = vkCreatePipelineLayout(dev, &ci, nullptr, &vk->text_layout);
        FLUX_VK_CHECK(res);
        if (res != VK_SUCCESS) return false;

        VkVertexInputAttributeDescription attrs[2] = {
            { .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = offsetof(flux_image_vertex, pos) },
            { .location = 1, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = offsetof(flux_image_vertex, uv) },
        };
        if (!make_pipeline_core(vk, vk->text_layout, vk->render_pass,
                                flux_image_vert_spv, sizeof(flux_image_vert_spv),
                                flux_text_frag_spv, sizeof(flux_text_frag_spv),
                                sizeof(flux_image_vertex), attrs, 2,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                0xF,
                                VK_STENCIL_OP_KEEP, VK_COMPARE_OP_EQUAL, 0x00, 0,
                                &vk->text_pipeline)) return false;
    }

    /* gradient */
    {
        VkPushConstantRange push = {
            .stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
            .offset = 0, .size = sizeof(flux_gradient_pc),
        };
        VkPipelineLayoutCreateInfo ci = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
            .pushConstantRangeCount = 1, .pPushConstantRanges = &push,
        };
        VkResult res = vkCreatePipelineLayout(dev, &ci, nullptr, &vk->gradient_layout);
        FLUX_VK_CHECK(res);
        if (res != VK_SUCCESS) return false;

        VkVertexInputAttributeDescription attr = {
            .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0,
        };
        if (!make_pipeline_core(vk, vk->gradient_layout, vk->render_pass,
                                flux_gradient_vert_spv, sizeof(flux_gradient_vert_spv),
                                flux_gradient_frag_spv, sizeof(flux_gradient_frag_spv),
                                sizeof(flux_solid_vertex), &attr, 1,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                0xF,
                                VK_STENCIL_OP_KEEP, VK_COMPARE_OP_EQUAL, 0x00, 0,
                                &vk->gradient_pipeline)) return false;
    }

    /* stencil (clip path) */
    {
        VkPushConstantRange push = {
            .stageFlags = VK_SHADER_STAGE_VERTEX_BIT, .offset = 0, .size = sizeof(flux_solid_color_pc),
        };
        VkPipelineLayoutCreateInfo ci = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
            .pushConstantRangeCount = 1, .pPushConstantRanges = &push,
        };
        VkResult res = vkCreatePipelineLayout(dev, &ci, nullptr, &vk->stencil_layout);
        FLUX_VK_CHECK(res);
        if (res != VK_SUCCESS) return false;

        VkVertexInputAttributeDescription attr = {
            .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0,
        };
        if (!make_pipeline_core(vk, vk->stencil_layout, vk->render_pass,
                                flux_solid_color_vert_spv, sizeof(flux_solid_color_vert_spv),
                                flux_stencil_frag_spv, sizeof(flux_stencil_frag_spv),
                                sizeof(flux_solid_vertex), &attr, 1,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ZERO, VK_BLEND_FACTOR_ONE,
                                VK_BLEND_FACTOR_ZERO, VK_BLEND_FACTOR_ONE,
                                0xF,
                                VK_STENCIL_OP_REPLACE, VK_COMPARE_OP_ALWAYS, 0xFF, 1,
                                &vk->stencil_pipeline)) return false;
    }

    /* fill stencil (increment) */
    {
        VkVertexInputAttributeDescription attr = {
            .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0,
        };
        if (!make_pipeline_core(vk, vk->stencil_layout, vk->render_pass,
                                flux_solid_color_vert_spv, sizeof(flux_solid_color_vert_spv),
                                flux_stencil_frag_spv, sizeof(flux_stencil_frag_spv),
                                sizeof(flux_solid_vertex), &attr, 1,
                                VK_FALSE,
                                0, 0, 0, 0,
                                0,
                                VK_STENCIL_OP_INCREMENT_AND_CLAMP, VK_COMPARE_OP_ALWAYS, 0xFF, 0,
                                &vk->fill_stencil_pipeline)) return false;
    }

    /* solid cover */
    {
        VkVertexInputAttributeDescription attr = {
            .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0,
        };
        if (!make_pipeline_core(vk, vk->solid_layout, vk->render_pass,
                                flux_solid_color_vert_spv, sizeof(flux_solid_color_vert_spv),
                                flux_solid_color_frag_spv, sizeof(flux_solid_color_frag_spv),
                                sizeof(flux_solid_vertex), &attr, 1,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                0xF,
                                VK_STENCIL_OP_KEEP, VK_COMPARE_OP_EQUAL, 0x00, 1,
                                &vk->solid_cover_pipeline)) return false;
    }

    /* gradient cover */
    {
        VkVertexInputAttributeDescription attr = {
            .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0,
        };
        if (!make_pipeline_core(vk, vk->gradient_layout, vk->render_pass,
                                flux_gradient_vert_spv, sizeof(flux_gradient_vert_spv),
                                flux_gradient_frag_spv, sizeof(flux_gradient_frag_spv),
                                sizeof(flux_solid_vertex), &attr, 1,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                0xF,
                                VK_STENCIL_OP_KEEP, VK_COMPARE_OP_EQUAL, 0x00, 1,
                                &vk->gradient_cover_pipeline)) return false;
    }

    /* blur */
    {
        typedef struct { float surface_size[2], pad[2], texel_size[2]; } flux_blur_pc;
        VkPushConstantRange push = {
            .stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
            .offset = 0, .size = sizeof(flux_blur_pc),
        };
        VkPipelineLayoutCreateInfo ci = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
            .setLayoutCount = 1, .pSetLayouts = &vk->image_dsl,
            .pushConstantRangeCount = 1, .pPushConstantRanges = &push,
        };
        VkResult res = vkCreatePipelineLayout(dev, &ci, nullptr, &vk->blur_layout);
        FLUX_VK_CHECK(res);
        if (res != VK_SUCCESS) return false;

        VkVertexInputAttributeDescription attrs[2] = {
            { .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = offsetof(flux_image_vertex, pos) },
            { .location = 1, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = offsetof(flux_image_vertex, uv) },
        };
        if (!make_pipeline_core(vk, vk->blur_layout, vk->render_pass,
                                flux_image_vert_spv, sizeof(flux_image_vert_spv),
                                flux_blur_frag_spv, sizeof(flux_blur_frag_spv),
                                sizeof(flux_image_vertex), attrs, 2,
                                VK_TRUE,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                0xF,
                                VK_STENCIL_OP_KEEP, VK_COMPARE_OP_EQUAL, 0x00, 0,
                                &vk->blur_pipeline)) return false;
    }

    vk->pipelines_ready = true;
    return true;
}
